.TH "lsusb" "1" "November 2013" "Homebrew" "lsusb for Mac OS X"
.
.SH "NAME"
\fBlsusb\fR - list attached USB devices
.
.SH "SYNOPSIS"
\fBlsusb\fR [\-hv] [\-d DEVICE]

.SH "DESCRIPTION"
Lists USB devices in Mac OS X, like the \fBlsusb\fR command in Linux.

This utility is built on the output of \fB\fCsystem_profiler\fR.

  -h         display this help and exit
  -v         show the raw output of `system_profiler SPUSBDataType`
  -d DEVICE  list only devices which match DEVICE

DEVICE is [vendorId][:productId], ids in hexadecimal.

.SH "SEE ALSO"
/usr/sbin/system_profiler, https://github.com/jlhonora/lsusb

.SH "AUTHORS"
Jose L. Honorato <jlhonora@ing.puc.cl>
.fi
