#!/usr/bin/env bash
# lsusb utility for Mac OS X
# Author: JLH, Sep 2013

system_profiler SPUSBDataType > sp_info.log
devices=`grep -B 2 -A 1 "Product ID" sp_info.log | sed 's/^--/#/'`

OIFS=$IFS
IFS="#"
counter=0

for device in $devices 
do
	name=`echo $device | head -2 | grep ":$"  | sed -e 's/^ *//g' -e 's/ *:$//g'`
	PID=`echo $device | grep "Product ID" | awk -F':' '{print $2}' | sed -e 's/0x//; s/^ *//g' -e 's/ *$//g'`
	if [ -z "$PID" ]; then
		continue
	fi
	VID=`echo $device | grep "Vendor ID" | awk -F':' '{print $2}' | sed -e 's/0x//; s/^ *//g' -e 's/ *$//g'`
	if [ -z "$VID" ]; then
		continue
	fi
	bus_num=`grep -B 100 "$PID" sp_info.log | grep "Bus Number" | tail -1 | sed -e 's/Bus Number://' -e 's/0x//; s/^ *//g' -e 's/ *$//g'`
	echo "Bus $bus_num ID $PID:$VID $name"
done

IFS=$OIFS
rm sp_info.log
